sudo: required
services: 
  - docker

before_install:
  - docker build -t alvinyau/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true alvinyau/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "frontend"
  env: "Front-end-env"
  bucket_name: "elasticbeanstalk-us-east-1-975050339229"
  bucket_path: "frontend"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"


  